server:
  port: 9000

spring:
  application:
    name: Fraud
  datasource:
    url: jdbc:postgresql://postgres:5432/fraud
    username: 'postgres'
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
